### ISSUE TITLE
Shared libraries?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/lemon-feedstock#1]
Appears that only static libraries are built and included in this package. Is it possible to build and package shared libraries as well?

**Comment by jakirkham** [comment]
As far as this goes, saw that the CMake configuration file that LEMON provides hard codes static libraries into it. So this is either intentional or a bug. Not really sure which.

If we do end up with only static libraries for LEMON as the resolution, it raises the question as to how things like GLPK work in this context. Currently LEMON is dynamically linked to GLPK. Perhaps there is a way to force LEMON to statically link to GLPK and other dependencies? This would make it easier to manage LEMON as a dependency, but maybe there are other issues with this approach.

**Comment by stuarteberg** [comment]
Since no one else is chiming in with an opinion, I think we can feel free to just build dynamic libraries (and not static ones).  Nice catch regarding the configuration file.

**Comment by jakirkham** [comment]
So do you want to patch it then?

**Comment by stuarteberg** [comment]
See #3

**Comment by jakirkham** [comment]
Sorry missed that there was a PR already.
