### ISSUE TITLE
Remove win-64/lemon-1.3.1-h7f30438_2.tar.bz2 from main channel

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/lemon-feedstock#19]
The lemon package `win-64/lemon-1.3.1-h7f30438_2.tar.bz2` is shipped as a debug version and will not work when linked to release binaries...

**Comment by jakirkham** [comment]
Can you please send a PR to [admin-requests]( https://github.com/conda-forge/admin-requests ) as [described here]( https://github.com/conda-forge/admin-requests#mark-packages-as-broken-on-conda-forge )?

**Comment by k-dominik** [comment]
thanks @jakirkham, will do! Always something new to learn in the conda-forge universe
