### ISSUE TITLE
Lemon not building with new compiler stack on Mac, problems on windows

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/lemon-feedstock#6]
Issue: After re-rendering with `conda-smithy`, this recipe will only successfully build on linux.
See here: https://github.com/conda-forge/lemon-feedstock/pull/5

I'll look into it later today - just opened an issue in case someone feels like joining :)

**Comment by jakirkham** [comment]
It looks like this has since been fixed. Going to go ahead and close. Please let us know if that is not the case though.
